### ISSUE TITLE
sf_to_geoda removes all columns from sf object

### ISSUE THREAD

**Issue by angela-li** [GeoDaCenter/rgeoda#1]
When you try to convert an sf object to a geoda object, it removes all the columns of the sf object. 

I'm using the guerry sf object from the teaching [geodaData package](https://github.com/spatialanalysis/geodaData) here.

```
library(geodaData)
library(rgeoda)
guerry_sf <- geodaData::guerry
guerry_geoda <- rgeoda::sf_to_geoda(guerry_sf)
#> Loading required package: sf
#> Linking to GEOS 3.7.2, GDAL 2.4.2, PROJ 5.2.0
#> Loading required package: wkb
guerry_geoda
#> Reference class object of class "geoda"
#> Field "gda":
#> An object of class "_p_GeoDa"
#> Slot "ref":
#> <pointer: 0x7fcbfbf7c810>
#> 
#> Field "map_type":
#> [1] "polygon_type"
#> Field "n_cols":
#> [1] 0
#> Field "n_obs":
#> [1] 85
#> Field "field_names":
#> character(0)
#> Field "field_types":
#> character(0)
#> Field "table":
#> data frame with 0 columns and 85 rows

```

**Comment by angela-li** [comment]
Hm, I realize that the default is `with_table = FALSE`, which is why this is happening. I'm wondering if it would make more sense to set it to TRUE, so people don't think it's an error when they read in their data...

**Comment by lixun910** [comment]
Sounds good. I didn’t think about it from a user perspective. Will change
it to True by default.

FYI I did it on purpose: 1. when you have an sf object with table data,
rgeoda can  be created with only geometries for weights creation, and one
can always pass the table data (tuple or vector) directly from sf to rgeoda
function (see the example of rgeoda+sf). 2. copy the existing table from sf
to rgeoda will take some time especially when you have a big table.  3.
When you use rgeoda to load data (eg assume no sf) it will create a table
by default.

Thanks!
