### ISSUE TITLE
rgeoda removed from CRAN

### ISSUE THREAD

**Issue by fgoerlich** [GeoDaCenter/rgeoda#15]
Hi,
rgeoda has recently been removed from [CRAN](https://cran.r-project.org/web/packages/rgeoda/index.html).
Is this going to be changed in the near future?
Thanks a lot.

**Comment by lixun910** [comment]
Thanks, @fgoerlich We are working on v0.0.8 now and will submit it to CRAN soon.

**Comment by lixun910** [comment]
back to CRAN
