### ISSUE TITLE
How to load saved weight

### ISSUE THREAD

**Issue by olaTechie** [GeoDaCenter/rgeoda#17]
Hi,

Please how can one load the saved load weight or .gwt file generated from the desktop Geoda?

Thanks a lot for porting this to R.

**Comment by lixun910** [comment]
@olaTechie yes, this is on our to-do list. It will be in next release v0.1.0. Will keep you updated. Thanks!

**Comment by olaTechie** [comment]
Thanks a lot looking forward it

**Comment by lixun910** [comment]
@olaTechie rgeoda 0.0.8-3 added some functions to read weights file: read_gal(), read_gwt(), read_swm();  
`as.matrix(w)` to convert weights to matrix that can be used in e.g. spdep. See the examples:
```R
# create a weights
guerry_path <- system.file("extdata", "Guerry.shp", package = "rgeoda")
guerry <- st_read(guerry_path)
queen_w <- queen_weights(guerry)
save_weights(queen_w, guerry['CODE_DE'], '/tmp/guerry1.gal')
# read it back to rgeoda
w <- read_gal('/tmp/guerry1.gal', guerry['CODE_DE'][[1]])
```
`read_swm()` for ESRI's spatial weights format
```R
w <- read_swm('/tmp/virginia_queen.swm')
#testthat::expect_equal(w$sparsity, 0.03168253)
```
One can also create an empty weights using `create_weights()`, and assign neighbors `set_neighbors()` or `set_neighbors_with_weights()` manually. See the example:
```R
w <- create_weights(3)
set_neighbors(w, 1, c(2,3))
set_neighbors(w, 2, c(1,3))
set_neighbors(w, 3, c(1,2))
update_weights(w)
```
Let me know if these functions work as expected. Thanks!

**Comment by olaTechie** [comment]
@lixun910 Thanks a lot for the update and for providing clarifications on how to work with the weight.
