### ISSUE TITLE
the color may be wrong for LISA mapping

### ISSUE THREAD

**Issue by ynsxx** [GeoDaCenter/rgeoda#18]
Dear Prof. Li
When I run the rgeoda for my data, I found the legend color may be inconsistent with the results of geoda software  (low-high and high-low). see the graph below: 
![image](https://user-images.githubusercontent.com/12133270/125020199-030ac900-e0ab-11eb-8729-16ca6594f62e.png)

**Comment by lixun910** [comment]
Thanks, @ynsxx !  I think the color matches, but the return of `lisa_labels` should be "Low-High" and "High-Low".
You can pass your own labels for a workaround. I will submit a fix to CRAN and let you know.

**Comment by lixun910** [comment]
@ynsxx This issue should be fixed in rgeoda 0.0.8-3 https://cran.r-project.org/web/packages/rgeoda/index.html
Thanks again!

**Comment by ynsxx** [comment]
Thank You. I got It. Thank you for your hard work and effort. 肖肖宋 ***@***.*** 签名由 网易邮箱大师 定制 On 07/28/2021 08:05, Xun Li wrote: @ynsxx This issue should be fixed in rgeoda 0.0.8-3 https://cran.r-project.org/web/packages/rgeoda/index.html Thanks again! — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
