### ISSUE TITLE
Create weights for sf with tibble classes

### ISSUE THREAD

**Issue by sdesabbata** [GeoDaCenter/rgeoda#19]
Hi,

When loading geographic data using `read_sf` instead of `st_read`, the resulting `sf` object has four classes. As such, the condition `length(class(obj)) == 2` in line 86 of `sf_geoda.R` seems to block the casting of the `sf` object to `geoda` object. I would suggest changing the condition to allow objects with both 2 and 4 classes.

Line 86 of `sf_geoda.R`:

```
  } else if (length(class(obj)) == 2 && class(obj)[[1]] == "sf") {
```

Using `st_read`:

```
> st_read_loac <- st_read("Shapefile_London/LOAC.shp")
> class(st_read_loac)
[1] "sf"         "data.frame"
> length(class(st_read_loac))
[1] 2
```

Using `read_sf`:

```
> read_sf_loac <- read_sf("Shapefile_London/LOAC.shp")
> class(read_sf_loac)
[1] "sf"         "tbl_df"     "tbl"        "data.frame"
> length(class(read_sf_loac))
[1] 4
```

**Comment by lixun910** [comment]
Thank you! @sdesabbata I can change the condition to allow objects with both 2 and 4 classes. One possible change is: 
```R
} else if (length(class(obj)) >= 2 && class(obj)[[1]] == "sf") {
```
What do you think?

**Comment by sdesabbata** [comment]
Sure, I guess that should work. Depending on whether you just need to check whether `sf` is one of the classes, the code below might also work. I guess it depends on what `sf_to_geoda` does, that is how the `geoda` object is constructed.

```
} else if ("sf" %in% class(obj)) {
```

**Comment by lixun910** [comment]
@sdesabbata Yes, that's the R style (that I am not good at)! 👍Thanks very much! Let me know if you want to commit this change to the repo. I will submit a new version tomorrow.

**Comment by sdesabbata** [comment]
@lixun910 I edited the code, creating a check using the `inherits`, which seemed overall more appropriate to the context, and created a pull request. I hope that works fine. 😄 

Thanks so much for your fantastic work on this library!

**Comment by lixun910** [comment]
You are welcome, @sdesabbata Yes, `inherits(obj, "sf")` is even better! I saw your pull request. Will work on it and create a new version. Thank you again!
