### ISSUE TITLE
Weight creation from polygons wrong

### ISSUE THREAD

**Issue by rsbivand** [GeoDaCenter/rgeoda#21]
It seems that `queen_weights()` is wrong (unzip attached file) in CRAN version 0.0.8.3:
[chk.zip](https://github.com/GeoDaCenter/rgeoda/files/6923951/chk.zip)

```
library(sf)
chk <- st_read("chk.gpgk")
library(rgeoda)
get_neighbors(rook_weights(chk, precision_threshold=sqrt(.Machine$double.eps)), 1)
get_neighbors(queen_weights(chk, precision_threshold=sqrt(.Machine$double.eps)), 1)
library(spdep)
poly2nb(chk, queen=FALSE)[[1]]
poly2nb(chk, queen=TRUE)[[1]]
```
From examining the geometries, the single coordinate on the borders of 1 and 6 is ignored:
```
plot(st_geometry(chk))
text(st_coordinates(st_centroid(st_geometry(chk))))
```

**Comment by lixun910** [comment]
Thank you, @rsbivand I can replicate it on my side. I was able to locate the issue in the libgeoda code: it is a bug that the double-precision epsilon was not handled in the weights creation code. I will commit a fix and create a new build.

**Comment by rsbivand** [comment]
Thanks, I can confirm that this works now as expected!
