### ISSUE TITLE
Error when using "sf"    "grouped_df" "tbl_df"    "tbl"      "data.frame"  in queen_weights()

### ISSUE THREAD

**Issue by PauGallesClara** [GeoDaCenter/rgeoda#23]
Hi ! 
I get this error "Error in as.geoda(sf_obj, with_table = FALSE) :  as.geoda() takes either an 'sf' or 'sp' object. "  when using queen_weights ().  
I'm using a class object   "sf"    "grouped_df" "tbl_df"    "tbl"    "data.frame"  and I thought that because is an sf one i could run properly. What am I missing ?

Thank you in advance

**Comment by lixun910** [comment]
Thanks, @PauGallesClara ! I think this issue is related to https://github.com/GeoDaCenter/rgeoda/issues/19, which has been fixed in version 0.0.8-4. What is the version of rgeoda your are using? Could you try version 0.0.8-4 to see if this issue has been addressed? Thank you!

**Comment by PauGallesClara** [comment]
Yes, the problem is solved by updating the rgeoda package to 0.0.8-4 version

Many thanks
