### ISSUE TITLE
redcap (RStudio crashes)

### ISSUE THREAD

**Issue by oousmane** [GeoDaCenter/rgeoda#38]
My code 
library(sf)
library(rgeoda)

bf_geoda <- st_read(dsn = "shapefile/bf_geodata",
                    layer = "bf_zoning_data")

queen_w <- queen_weights(bf_geoda)
cls <- redcap(4, queen_w, bf_geoda["rain"],cpu_threads=1)

Also, skater return only 1 cluster and all metrics are NA. I don't know why but with guerry data everything is okay.
  
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/69334445/220731129-58fe2be1-398f-4be1-880f-41b08a529faa.png">

My Session Info : 

R version 4.2.2 (2022-10-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Ventura 13.0

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] compiler_4.2.2  tools_4.2.2     rstudioapi_0.14

**Comment by econmiller** [comment]
This appears to be open still, and I'm experiencing the same exact issue.

![image](https://github.com/GeoDaCenter/rgeoda/assets/77371053/d1da419b-8622-477c-8b7c-0d262f50c851)

This may be related to non-support for rgdal

**Comment by oousmane** [comment]
@econmiller Sorry, i forgot to close the issue. For me it was NA issue in my  dataset.

**Comment by oousmane** [comment]
By applying dplyr::drop_na(bf_geoda) it worked.

**Comment by econmiller** [comment]
Ah. I'll give it a shot. Many thanks!

Sent via the Samsung Galaxy S23+ 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
